language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
before_script:
  - composer self-update
  - composer update --prefer-source
  - composer install --dev --prefer-source
  - npm install -g grunt-cli
  - npm install
script: grunt travis